накидал моделей
alehandrodol/PerfectCookBook pull request #3
Opened 2023-10-03 18:00 UTC by Tidbid

Хз как пагинация работает и как у алхимии работают режимы подтягивания ассоциаций (lazy/eager), и будем ли мы вообще по этому поводу заморачиваться, но может ассоциации из моделек придется убрать.

2023-10-05 16:47 UTC, alehandrodol commented on backend/db/models/ingredients.py
> +    quantity = Column(String(128), nullable=False)
давай здесь ограничим до 32, у нас тут будет просто кол-во ингредиента, которое нам надо в блюде, не вижу кейса, где нужно более 32

2023-10-05 17:13 UTC, alehandrodol requested changes

2023-10-05 17:13 UTC, alehandrodol commented on backend/db/models/__init__.py
> +    "Ingredient"
Сюда нужно также добавить ассоциативные таблицы, так как отсюда берутся модели для создания миграций

2023-10-05 17:13 UTC, alehandrodol commented on backend/db/models/ingredients.py
> +    quantity = Column(String(128), nullable=False)
давай здесь ограничим до 32, у нас тут будет просто кол-во ингредиента, которое нам надо в блюде, не вижу кейса, где нужно более 32

2023-10-05 17:13 UTC, alehandrodol commented on backend/db/models/__init__.py
> +    "Ingredient"
Хотя если быть честным я не до конца в этом уверен, что это нужно, при учёте того, что там METADATA при создании таблицы, давай наверное не будем добавлять, смёрджим так, и если не заведётся, то добавим

2023-10-05 17:13 UTC, alehandrodol commented on backend/db/models/dishes.py
> +from backend.db.models.dish_tag import dish_tag_association_table
Для нашего приложения корневая папка будет backend, поэтому обращаясь к backend он не поймёт, к чему ты обращаешься, поэтом во всех местах, нужно убрать backend.db. и оставить просто db.

2023-10-06 17:00 UTC, Tidbid commented on backend/db/models/dishes.py
> +from backend.db.models.dish_tag import dish_tag_association_table
У меня пайчарм не резолвил без бэкенда, удалил

2023-10-06 17:01 UTC, Tidbid commented on backend/db/models/ingredients.py
> +    quantity = Column(String(128), nullable=False)
quantitiy столбец сделал String(32)

2023-10-06 19:44 UTC, alehandrodol approved these changes

2023-10-06 19:45 UTC, merged